### ISSUE TITLE
SHadj not working

### ISSUE THREAD

**Issue by mglev1n** [Osmahmoud/SlopeHunter#3]
The SHadj function doesn't appear to be working. It looks like the following line is the culprit: https://github.com/Osmahmoud/SlopeHunter/blob/d7c56a18ce6277e1cd4892697bd06b6b41e3cd32/R/SHadj.R#L34
Currently the function expects the correction factor to be held as "SH.b" within the output of `SlopeHunter::hunt()`:
`Sh.b <- x$Sh.b`

However, the correction factor is held as "b". Making the following adjustment to the code appears to solve the issue:
`Sh.b <- x$b`

**Comment by Osmahmoud** [comment]
Thank you - This has been fixed and updated in V1.0.0
